version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .

  mysql:
    container_name: mysql
    image: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=admin
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin
    - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  postgresql:
    image: postgres
    container_name: postgres
    ports:
      - "5436:5432"
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"

networks:
  default:
    name: backend
    external: true